Data Management (for INF-2700): test_data_gen.h File Reference
test_data_gen.h File Reference
Test data generator.
#include "schema.h"
Functions
schema_p create_test_schema (const char *name)
void reset_test_data_gen ()
void fill_gen_record (schema_p s, record r)
Detailed Description
Test data generator.
Author:
Weihai Yu
Definition in file test_data_gen.h.
Function Documentation
schema_p create_test_schema (const char * name)
create the test schema my_schema (MyIdField: int, MyStrField:str[TEST_STR_LEN], myIntField:int)
Definition at line 10 of file test_data_gen.c.
References add_field(), DEBUG, new_int_field(), new_schema(), new_str_field(), put_schema_info(), tbl_desc_struct::sch, and TEST_STR_LEN.
Referenced by test_rec_write().
void fill_gen_record (schema_p s, record r)
fill a record with some generated data.
values (id, my_schema_Val_id, rand())
Definition at line 27 of file test_data_gen.c.
References fill_record(), schema_name(), and TEST_STR_LEN.
Referenced by test_rec_write().
void reset_test_data_gen ()
resets the test data generator. next_test_record_id is set to 0
Definition at line 20 of file test_data_gen.c.
Referenced by test_rec_write().