Data Management (for INF-2700): schema.h File Reference
schema.h File Reference
Table schema.
#include "pager.h"
#include <stdarg.h>
Defines
#define MAX_STR_LEN 100
Typedefs
typedef struct field_desc_struct * field_desc_p
typedef struct schema_struct * schema_p
typedef struct record_struct * record_p
typedef struct tbl_desc_struct * tbl_p
typedef void ** record
Data record.
Enumerations
enum field_type { INT_TYPE, STR_TYPE }
enum tbl_position { TBL_BEG, TBL_END }
Functions
void put_field_info (pmsg_level level, field_desc_p f)
void put_record_info (pmsg_level level, record r, schema_p s)
void put_schema_info (pmsg_level level, schema_p s)
void put_tbl_info (pmsg_level level, tbl_p t)
void put_db_info (pmsg_level level)
int open_db (void)
void close_db (void)
schema_p new_schema (const char *name)
schema_p get_schema (const char *name)
void remove_schema (schema_p s)
char * schema_name (schema_p sch)
field_desc_p schema_first_fld_desc (schema_p sch)
field_desc_p schema_last_fld_desc (schema_p sch)
int schema_num_flds (schema_p sch)
int schema_len (schema_p sch)
field_desc_p new_int_field (const char *name)
field_desc_p new_str_field (const char *name, int len)
int is_int_field (field_desc_p f)
field_desc_p field_desc_next (field_desc_p f)
int add_field (schema_p s, field_desc_p f)
record new_record (schema_p s)
void release_record (record r, schema_p s)
void assign_int_field (void *field_p, int int_val)
void assign_str_field (void *field_p, char *str_val)
int fill_record (record r, schema_p s,...)
int equal_record (record r1, record r2, schema_p s)
void set_tbl_position (tbl_p t, tbl_position pos)
int get_record (record r, schema_p s)
int put_record (record r, schema_p s)
int append_record (record r, schema_p s)
tbl_p get_table (const char *name)
void remove_table (tbl_p t)
void table_display (tbl_p s)
tbl_p table_search (tbl_p t, char *attr, char *op, int val)
tbl_p table_project (tbl_p t, const char *dest_name, int num_fields, char *fields[])
Variables
tbl_p db_tables
Database tables.
Detailed Description
Table schema.
Author:
Weihai Yu
A table schema defines a number of data fields. A table record holds the data values whose types are defined in the schema.
Use new_schema() to create an empty new schema, new_int_field() and new_str_field() to create a new field, and add_field() to add a field to a schema.
Use get_schema() to get a schema, and schema_first_fld_desc(), schema_last_fld_desc() and field_desc_next() to nevigate through the fields of the schema.
Since the data types of record fields are not known at compile time, generic pointer (void *) is used in many places and must be cast to the right C types. The types of a record's fields are maintained in field descriptors of the corresponding schema. Therefore operations on records and record fields are typically associated with a schema, and navigating the fields of a record involves navigating in parallel the field descriptors of the schema. See the source code of put_record_info and fill_record ect. as examples of how to access field values of a record.
The memory of a record is allocated with new_record() and released with release_record(). Assign field valuse to a record with assign_int_field(), assign_str_field() or fill_record(). Compare if two records have equal values with equal_record(). Access the record at the current position of a page with get_record() and put_record().
Definition in file schema.h.
Define Documentation
#define MAX_STR_LEN 100
Definition at line 47 of file schema.h.
Typedef Documentation
typedef struct field_desc_struct* field_desc_p
Definition at line 52 of file schema.h.
typedef void** record
Data record.
A record consists of an array of pointers to field values. Because in general, the types of the fields of a record are unknown at compile time, the memory of these values has to be allocated at run time with new_record. When accessing these values, the generic (void *) pointers must be casted to the correct C types (int *) and (char *). See the source code of put_record_info and fill_record as examples of how to access field values of a record.
Definition at line 67 of file schema.h.
typedef struct record_struct* record_p
Definition at line 54 of file schema.h.
typedef struct schema_struct* schema_p
Definition at line 53 of file schema.h.
typedef struct tbl_desc_struct* tbl_p
Definition at line 55 of file schema.h.
Enumeration Type Documentation
enum field_type
Enumerator:
INT_TYPE
STR_TYPE
Definition at line 49 of file schema.h.
enum tbl_position
Enumerator:
TBL_BEG
TBL_END
Definition at line 50 of file schema.h.
Function Documentation
int add_field (schema_p s, field_desc_p f)
Add a field to the schema
Definition at line 445 of file schema.c.
References BLOCK_SIZE, ERROR, schema_struct::first, schema_struct::last, field_desc_struct::len, schema_struct::len, field_desc_struct::next, schema_struct::num_fields, field_desc_struct::offset, PAGE_HEADER_SIZE, and put_msg().
Referenced by create_test_schema().
int append_record (record r, schema_p s)
Append the record to the table file. The current position moves to the new end of the file. Returns -1 if there is some fatal failure.
Definition at line 716 of file schema.c.
References tbl_desc_struct::current_pg, FATAL, get_next_page(), get_page_for_append(), schema_struct::name, tbl_desc_struct::num_records, page_block_nr(), put_msg(), schema_struct::tbl, and unpin().
Referenced by table_project(), table_search(), and test_rec_write().
void assign_int_field (void * field_p, int int_val)
Assign an int record field. Note the data type of field_pp
Definition at line 506 of file schema.c.
Referenced by fill_record().
void assign_str_field (void * field_p, char * str_val)
Assign a str record field. Note the data type of field_pp
Definition at line 511 of file schema.c.
Referenced by fill_record().
void close_db (void)
Close a database
Definition at line 328 of file schema.c.
References db_tables, and pager_terminate().
Referenced by test_rec_read(), and test_rec_write().
int equal_record (record r1, record r2, schema_p s)
Compare if two records have equal field values
Definition at line 555 of file schema.c.
References ERROR, schema_struct::first, is_int_field(), field_desc_struct::next, and put_msg().
Referenced by test_rec_read().
field_desc_p field_desc_next (field_desc_p f)
Returns the next field_desc
Definition at line 160 of file schema.c.
References ERROR, field_desc_struct::next, and put_msg().
int fill_record (record r, schema_p s, ...)
Fill a record with values. Example: fill_record (r, s, 1, "A string", 136)
Definition at line 516 of file schema.c.
References assign_int_field(), assign_str_field(), ERROR, schema_struct::first, is_int_field(), field_desc_struct::next, and put_msg().
Referenced by fill_gen_record().
int get_record (record r, schema_p s)
Retrieve the record value at the current position. The current position moves to the next record. Returns 1 when r is updated, 0 when there is no more record, and -1 when something goes wrong.
Definition at line 648 of file schema.c.
Referenced by table_display(), table_project(), and test_rec_read().
schema_p get_schema (const char * name)
Return an existing schema, NULL if the named schema does not exist.
Definition at line 356 of file schema.c.
References get_table(), and tbl_desc_struct::sch.
Referenced by test_rec_read(), and test_rec_write().
tbl_p get_table (const char * name)
Return an existing table desc, NULL if the table does not exist.
Definition at line 347 of file schema.c.
References db_tables, schema_struct::name, tbl_desc_struct::next, and tbl_desc_struct::sch.
Referenced by get_schema(), and test_rec_read().
int is_int_field (field_desc_p f)
Check if this is an int field. Since there are only int and str fields, "not int" means str.
Definition at line 153 of file schema.c.
References INT_TYPE, and field_desc_struct::type.
Referenced by equal_record(), fill_record(), put_field_info(), put_record(), and put_record_info().
field_desc_p new_int_field (const char * name)
Make an int field with name name.
Definition at line 120 of file schema.c.
References INT_SIZE, INT_TYPE, field_desc_struct::len, field_desc_struct::name, field_desc_struct::next, field_desc_struct::offset, and field_desc_struct::type.
Referenced by create_test_schema().
record new_record (schema_p s)
Creates a new record of schema s. It is the responsibility of the using program to free the memory of the resulting record using release_record().
Definition at line 472 of file schema.c.
References ERROR, schema_struct::first, field_desc_struct::len, field_desc_struct::next, schema_struct::num_fields, and put_msg().
Referenced by table_display(), table_project(), table_search(), test_rec_read(), and test_rec_write().
schema_p new_schema (const char * name)
Make a new schema and add it to the current database
Definition at line 335 of file schema.c.
References tbl_desc_struct::current_pg, db_tables, tbl_desc_struct::next, tbl_desc_struct::num_records, tbl_desc_struct::sch, and schema_struct::tbl.
Referenced by create_test_schema().
field_desc_p new_str_field (const char * name, int len)
Make an string field with name name and length len.
Definition at line 132 of file schema.c.
References field_desc_struct::len, field_desc_struct::name, field_desc_struct::next, field_desc_struct::offset, STR_TYPE, and field_desc_struct::type.
Referenced by create_test_schema().
int open_db (void)
Open a database at new_db_dir. If dir is NULL, re-open a prviously openned database. return -1 upon failure.
Definition at line 320 of file schema.c.
References pager_init(), and pager_terminate().
Referenced by test_rec_read(), and test_rec_write().
void put_db_info (pmsg_level level)
Definition at line 109 of file schema.c.
References db_tables, tbl_desc_struct::next, put_msg(), put_tbl_info(), and system_dir().
Referenced by test_rec_write().
void put_field_info (pmsg_level level, field_desc_p f)
Definition at line 44 of file schema.c.
References append_msg(), is_int_field(), field_desc_struct::len, field_desc_struct::name, field_desc_struct::next, field_desc_struct::offset, and put_msg().
Referenced by put_schema_info().
int put_record (record r, schema_p s)
Put the record value at the current position. The current position moves to the next record. Returns -1 if there is not enough space at current position.
Definition at line 698 of file schema.c.
References tbl_desc_struct::current_pg, schema_struct::first, is_int_field(), field_desc_struct::len, field_desc_struct::next, page_put_int(), page_put_str(), and schema_struct::tbl.
void put_record_info (pmsg_level level, record r, schema_p s)
Definition at line 91 of file schema.c.
References append_msg(), schema_struct::first, is_int_field(), field_desc_struct::next, and put_msg().
Referenced by table_project(), table_search(), and test_rec_read().
void put_schema_info (pmsg_level level, schema_p s)
Definition at line 63 of file schema.c.
References schema_struct::first, schema_struct::len, schema_struct::name, field_desc_struct::next, schema_struct::num_fields, put_field_info(), and put_msg().
Referenced by create_test_schema(), and put_tbl_info().
void put_tbl_info (pmsg_level level, tbl_p t)
Definition at line 78 of file schema.c.
References schema_struct::name, tbl_desc_struct::num_records, put_file_info(), put_msg(), put_schema_info(), and tbl_desc_struct::sch.
Referenced by put_db_info().
void release_record (record r, schema_p s)
Release the memory allocated for the record and its fields.
Definition at line 491 of file schema.c.
References ERROR, schema_struct::num_fields, and put_msg().
Referenced by table_display(), table_project(), table_search(), and test_rec_read().
void remove_schema (schema_p s)
Remove a schema from the current database
Definition at line 386 of file schema.c.
References remove_table(), and schema_struct::tbl.
Referenced by test_rec_write().
void remove_table (tbl_p t)
Remove a table from the current database
Definition at line 365 of file schema.c.
References close_file(), db_tables, schema_struct::name, tbl_desc_struct::next, and tbl_desc_struct::sch.
Referenced by remove_schema().
field_desc_p schema_first_fld_desc (schema_p sch)
Return the first field_desc of schema.
Definition at line 209 of file schema.c.
References ERROR, schema_struct::first, and put_msg().
field_desc_p schema_last_fld_desc (schema_p sch)
Return the last field_desc of schema.
Definition at line 219 of file schema.c.
References ERROR, schema_struct::last, and put_msg().
int schema_len (schema_p sch)
Return length of schema in number of bytes.
Definition at line 239 of file schema.c.
References ERROR, schema_struct::len, and put_msg().
char* schema_name (schema_p sch)
Return name of schema.
Definition at line 199 of file schema.c.
References ERROR, schema_struct::name, and put_msg().
Referenced by fill_gen_record().
int schema_num_flds (schema_p sch)
Return number of fields in schema.
Definition at line 229 of file schema.c.
References ERROR, schema_struct::num_fields, and put_msg().
void set_tbl_position (tbl_p t, tbl_position pos)
Set the current position to the beginning or end of the table.
Definition at line 581 of file schema.c.
References tbl_desc_struct::current_pg, get_page(), get_page_for_append(), schema_struct::name, page_set_pos_begin(), tbl_desc_struct::sch, TBL_BEG, and TBL_END.
Referenced by table_display(), table_project(), table_search(), and test_rec_read().
void table_display (tbl_p s)
Print all rows of a table.
Definition at line 786 of file schema.c.
References FORCE, get_record(), new_record(), put_msg(), release_record(), tbl_desc_struct::sch, set_tbl_position(), and TBL_BEG.
tbl_p table_project (tbl_p t, const char * dest_name, int num_fields, char * fields[])
Make a new table as a result of project.
Definition at line 839 of file schema.c.
References append_record(), DEBUG, get_record(), new_record(), put_record_info(), release_record(), tbl_desc_struct::sch, set_tbl_position(), schema_struct::tbl, and TBL_BEG.
tbl_p table_search (tbl_p t, char * attr, char * op, int val)
search src table, put results in dest table.
Definition at line 803 of file schema.c.
References append_record(), DEBUG, ERROR, find_record_int_val(), schema_struct::first, INT_TYPE, schema_struct::name, field_desc_struct::name, new_record(), field_desc_struct::next, field_desc_struct::offset, put_msg(), put_record_info(), release_record(), tbl_desc_struct::sch, set_tbl_position(), schema_struct::tbl, TBL_BEG, and field_desc_struct::type.
Variable Documentation
tbl_p db_tables
Database tables.
a linked list of table descriptors
Definition at line 70 of file schema.h.
Referenced by close_db(), get_table(), new_schema(), put_db_info(), and remove_table().