Data Management (for INF-2700): testschema.c File Reference
testschema.c File Reference
#include "testschema.h"
#include "test_data_gen.h"
#include "pmsg.h"
Defines
#define NUM_RECORDS 1000
Functions
void test_rec_write (const char *sch_name)
void test_rec_read (const char *sch_name)
Variables
record in_recs [NUM_RECORDS]
Define Documentation
#define NUM_RECORDS 1000
Definition at line 5 of file testschema.c.
Referenced by test_rec_read(), and test_rec_write().
Function Documentation
void test_rec_read (const char * sch_name)
Definition at line 46 of file testschema.c.
References close_db(), equal_record(), FATAL, get_record(), get_schema(), get_table(), in_recs, INFO, new_record(), NUM_RECORDS, open_db(), put_msg(), put_pager_profiler_info(), put_record_info(), release_record(), tbl_desc_struct::sch, set_tbl_position(), and TBL_BEG.
Referenced by main().
void test_rec_write (const char * sch_name)
Definition at line 12 of file testschema.c.
References append_record(), close_db(), create_test_schema(), DEBUG, fill_gen_record(), get_schema(), in_recs, INFO, new_record(), NUM_RECORDS, open_db(), put_db_info(), put_msg(), put_pager_profiler_info(), remove_schema(), reset_test_data_gen(), and tbl_desc_struct::sch.
Referenced by main().
Variable Documentation
record in_recs[NUM_RECORDS]
Definition at line 9 of file testschema.c.
Referenced by test_rec_read(), and test_rec_write().