Data Management (for INF-2700): testschema.h File Reference
testschema.h File Reference
#include "schema.h"
Functions
void test_rec_write (const char *sch_name)
void test_rec_read (const char *sch_name)
Function Documentation
void test_rec_read (const char * sch_name)
Definition at line 46 of file testschema.c.
References close_db(), equal_record(), FATAL, get_record(), get_schema(), get_table(), in_recs, INFO, new_record(), NUM_RECORDS, open_db(), put_msg(), put_pager_profiler_info(), put_record_info(), release_record(), tbl_desc_struct::sch, set_tbl_position(), and TBL_BEG.
Referenced by main().
void test_rec_write (const char * sch_name)
Definition at line 12 of file testschema.c.
References append_record(), close_db(), create_test_schema(), DEBUG, fill_gen_record(), get_schema(), in_recs, INFO, new_record(), NUM_RECORDS, open_db(), put_db_info(), put_msg(), put_pager_profiler_info(), remove_schema(), reset_test_data_gen(), and tbl_desc_struct::sch.
Referenced by main().